### ISSUE TITLE
Transform box trails go beyond the svg borders 

### ISSUE THREAD

**Issue by snikit** [ibrierley/Snap.svg.FreeTransform#6]
It happens only if you scale first .

If you move or rotat eand then do it , it works fine

![image](https://user-images.githubusercontent.com/10356702/44390620-5e6afc00-a54b-11e8-998a-6f34d9b4125f.png)

**Comment by ibrierley** [comment]
Have you tried the dev branch https://github.com/ibrierley/Snap.svg.FreeTransform/tree/development

**Comment by snikit** [comment]
Thanks Sir for the reply ,but I just did , the issue is still there

![image](https://user-images.githubusercontent.com/10356702/44400567-41ddbc80-a569-11e8-95f6-1292158078d1.png)

I'll also try to debug

**Comment by ibrierley** [comment]
Can you put your example on a fiddle or something to see, I can't get it to happen at http://svg.dabbles.info/Snap.svg.FreeTransform/ for example if I add a scale, but maybe I'm misunderstanding the order of things you are doing.

**Comment by snikit** [comment]
Silly me! the issue was with snap.svg version . I was Snap.svg 0.4.1 . I changed to 0.5.0 and it worked .
